[Xorg_xineramaproto]
git-tree-sha1 = "bf8ce8ede84365fd77614bbe12aa0d235d498284"

    [[Xorg_xineramaproto.download]]
    sha256 = "d781d464d8702bd5871ddca300b3b82ba7884c491e5c351e670c71ed9ee5d757"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xineramaproto_jll.jl/releases/download/Xorg_xineramaproto-v1.2.1+1/Xorg_xineramaproto.v1.2.1.any.tar.gz"
