# Autogenerated wrapper script for Xorg_xineramaproto_jll for any
JLLWrappers.@generate_wrapper_header("Xorg_xineramaproto")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
